### ISSUE TITLE
Is there any way to create new button by combining them together?

### ISSUE THREAD

**Issue by r3drains** [Ryochan7/antimicro#100] opened 2014-06-02 11:30 UTC
Hello,

I am having a issue when I need to press to create the combo skill. As to press on the gamepad buttons 1 + 2. Is there any way to create new button by combining them together?

**Comment by Ryochan7** [comment] 2015-03-30 15:39
Since this issue is mainly a duplicate of issue #50, this one isn't really necessary. Future discussion of this proposal should be done in issue #50. This issue is now closed.

**Closed by Ryochan7** 2015-03-30 15:39 UTC
Labels: enhancement
