### ISSUE TITLE
wont save 

### ISSUE THREAD

**Issue by AssFat** [Ryochan7/antimicro#229] opened 2015-09-11 22:45 UTC
much of the time when starting fresh or editing a micro for a certain button, it refuses to save or even leave what i put. example: i try to insert a pause, i close out to main program, there is no little save reminder icon, i go back ing to advanced settings, and all the changes ive made revert or disappeared. this happens quite often. then sometimes ill delete the whole line and start from scratch. then go back in an it has selectively chosen what to keep in. ill do the same on another set and it may or may not work fine.  
a copy paste is something ive been hoping you all would implement. it might help this situation as well as others.

**Comment by Ryochan7** [comment] 2015-09-12 06:55
Which version of antimicro are you using? I can only recall a couple of times in the past when some properties were not being properly flagged when edited. As long as the program detects that any property in a profile has been edited, a save icon should appear in the main combobox and the program will prompt you to save the profile if you try to exit the program.

As for copy paste, I guess it could technically be done. The classes being used to go through the XML should be able to work off of a regular string as well as a text file. I know Xpadder has that functionality but I never really used that feature.

**Comment by AssFat** [comment] 2015-09-12 10:35
im using the latest version and was even b4 i dl another copy today. ive found that if i keep inserting the same comands over and over it finally accepts. i must do this b4 i close the advanced window or it would not pre-save or what you call it. it usually does it with... actually it can do with anything. ive redone whole lines close save and go back into advanced and im like what the hell? this thing has a mind of its own sometimes or it pre-saves in strange intervals that should just happen then the advanced window is closed... at least. maybe its my pc. its def not junk. try to insert some "pause" commands for lets say .05 thats what i was trying to do. but not the first time at all. just the most in a row. took hours to do 10 or so lines. it was incredible.

**Comment by Ryochan7** [comment] 2015-09-12 17:49
I have tested and confirmed that inserting a Pause slot does not work properly in version 2.19.1. I will take a look into this problem and see what is going wrong.

**Comment by Ryochan7** [comment] 2015-09-12 18:04
Found the problem. An old, outdated method call that was being used for attempting to insert Pause slots. The call would constantly fail since no method had a matching signature. I have checked and confirmed that only inserting Pause slots is not working in the AdvanceButtonDialog window.

    QMetaObject::invokeMethod: No such method JoyButton::setAssignedSlot(int,int,int,int)
    Candidates are:
        setAssignedSlot(int,uint,int,JoyButtonSlot::JoySlotInputAction)
        setAssignedSlot(int,uint,int)
        setAssignedSlot(int,JoyButtonSlot::JoySlotInputAction)
        setAssignedSlot(int)
        setAssignedSlot(int,uint,JoyButtonSlot::JoySlotInputAction)
        setAssignedSlot(int,uint)
        setAssignedSlot(JoyButtonSlot*,int)

A fix for this problem should be in the repo in a matter of a few minutes. Thank you for mentioning this issue.

**Comment by AssFat** [comment] 2015-09-12 18:27
wow you are pretty awesome. thank you. i only stumbled on this help page while trying to dl the latest version. ill bring other probs to attn when i come across them. but seriously coulda swore i had this same issue with other commands.
cheers

**Comment by Ryochan7** [comment] 2015-09-12 19:20
There are probably some other problems elsewhere. I have checked inserting other slot types from that window and I checked the class's source code but I haven't find any other problem there.

**Comment by AssFat** [comment] 2015-09-12 19:38
so this fix will be in the next update?

**Comment by Ryochan7** [comment] 2015-09-13 06:35
It will be in the next update but I am not sure when I will package a new version yet. There are only a few other small tasks that I would want to get done before I would package a new patch version. Ideally, I could get a new version packaged in a couple of days.

**Closed** 2015-09-15 14:19 UTC
Labels: bug

**Comment by Ryochan7** [comment] 2015-09-18 22:32
I just found another problem like this one. Inserting blank slots will fail due to a method not being exposed as public. The problem was discovered while making some other changes. That issue has been fixed in the most recent commit.

**Comment by AssFat** [comment] 2015-09-19 16:56
yeah i remember that being a problem too. also i realized the other day my 4gh i5 cpu was overloaded. checked task manager and antimicro was taking 24%. that was after much altering of scripts. i rebooted it and all was fine. must get some kind of build up. was gonna keep an ey on it b4 i typed anything up... since im here i figured id mention it.
also many times the set changes get stuck. kinda one of the reasons i asked if there was a spot on this site to trade scripts for use and observation.
thanx

**Comment by Ryochan7** [comment] 2015-09-19 20:03
The only way that I have been able to reproduce that scenario is by setting two set change slots pointing back to each other on the same button in different sets; with that scenario, the sets will continuously change until Qt stops it. Although, since the slot type is supposed to behave like a One Way set selector, maybe the slot should actually be activated on a button release as opposed to a button press.

**Comment by AssFat** [comment] 2015-09-19 20:41
a text file is worth a thousand words. it may or may not be my fault. just thought id bring it up. i can send it, but unless ur playing the same game and all, you may never get stuck
