### ISSUE TITLE
Key Repeat on windows not working as intended

### ISSUE THREAD

**Issue by george-alisson** [Ryochan7/antimicro#180] opened 2015-03-30 16:16 UTC
The key repeat feature does not work as intended on windows since the key release event is not sent. In the code it is:
```c
// Send another key press to fake a key repeat
        sendevent(slot);
```
It does send a key press, but since the key release is not sent, the key is not repeated.
I just changed it to
```c
// Send another key press to fake a key repeat
        sendevent(slot, false);
        sendevent(slot, true);
```
and it is working now.

**Comment by Ryochan7** [comment] 2015-03-30 17:04
Based on the output from the Key Scan Codes program, that is how standard key repeating works on Windows. KeyDown events will keep being generated so that a key will be repeated in some applications. A KeyUp event is not sent until a key is actually released. I just checked in Notepad and key repeating is working as intended. Generating a KeyDown event followed by a KeyUp event is how turbo works in the program.

http://www.delphiforfun.org/programs/utilities/KeyCodes.htm

**Closed by Ryochan7** 2015-03-30 17:04 UTC
Labels: invalid

**Comment by george-alisson** [comment] 2015-03-30 17:16
Ok, if that is so, there are some games need the key release to repeat the keys, and it does not work as turbo, as the keys are detected as pressed in games, not as being hit. As I said, I tested it myself.

**Comment by Ryochan7** [comment] 2015-03-30 18:22
I have checked and Xpadder and Pinnacle work the same way. How does the game behave when using a real keyboard and mouse? When using Windows key repeating, the game shouldn't interpret the keys as being frequently pressed. That would likely break even standard WASD movement in games. The key should be interpreted in a game as constantly being held down. Windows key repeating is mainly meant for text editors and text boxes where key presses should be interpreted and performed after a set period of time. Another thing to mention is that only the last activated key is repeated.

Overall, it still seems like turbo mode should be used for that functionality. You might have to play with the turbo delay setting under the Advanced options in order to get the action to perform the way you want in game.

**Comment by george-alisson** [comment] 2015-03-30 22:11
No, it does not break any key press in any game I tried and it does not work as turbo. The switch from key press to release happens too fast to be detected as not pressing the key. I tried even at the slowest rate selectable in the gui (5/s) and it still works. I tried with 6 games now to confirm it and none was broken. I'm using this modified version. 

Yeah, my intention is that it will only repeat the last key, not the combination if there is one.

In fact, on Linux it works that way too. If you use xev when a real keyboard key is pressed, it will send key releases and key presses at the configured rate.

**Comment by Ryochan7** [comment] 2015-03-31 03:58
It is nice that X automatically handles that functionality instead of having to do that at the application level. X also does this in a Cygwin environment even when key repeating is not being simulated in antimicro.

I have tried adding a KeyUp event to key repeating just to see how things behave. In Notepad and LibreOffice, there isn't any difference that I can see. However, in the test Key Codes program that I linked earlier, it does show the repeated KeyUp events that are generated by antimicro with the change. KeyUp events are not shown during key repeating when using an actual keyboard on Windows.

**Comment by Ryochan7** [comment] 2015-04-23 19:49
While messing around with vmulti, I found that the behavior of the key repeat code being used when using SendInput was slightly inconsistent. On Windows, there is supposed to be a restart in the key repeat delay when a different key has been released; I double checked that behavior using a standard keyboard. antimicro has been changed so that the delay is started again if the last active key is still held when a different key has been released. Xpadder and PGP don't perform that release check so testing with those apps in this situation won't be as helpful.
