### ISSUE TITLE
Unusually high CPU usage

### ISSUE THREAD

**Issue by namuol** [Ryochan7/antimicro#217] opened 2015-08-22 07:24 UTC
Not sure what the cause is, but I get around 20% CPU usage constantly regardless of what layouts I use. This isn't terrible, but I do notice the performance hit since I primarily use AntiMicro on my laptop for gaming.

By comparison, QJoyPad doesn't even register when I run `top`, so I'd guess there's something funny going on here...

Anyone else experiencing this?

----

Edit: Here's my system info for posterity:

- Thinkpad X220
- Core i5-2450M CPU @ 2.50GHz
- Ubuntu 15.04
- Linux `3.19.0-26-generic`

**Comment by ssokolow** [comment] 2015-08-22 07:35
I'm running antimicro 2.18.1 from the PPA on a Lubuntu/Kubuntu 14.04 hybrid (Lubuntu 14.04 with kubuntu-desktop installed and selected) and, now that you prompted me to check, I just noticed that it idles around 16% CPU usage (with 100% being a single core) in htop with an XBox 360 pad connected.

More worryingly, it idles around 116% CPU usage (one entire core plus 16% of another) if started with no joysticks connected. (Because Linux lacks a joystick control panel and some games crash if given more than four joysticks, I have all my joysticks plugged into switchable USB hubs.)

**Comment by Ryochan7** [comment] 2015-08-22 18:39
The problem with high CPU usage when no joysticks are connected was fixed in version 2.18.1. The problem came about in version 2.18 due to the refactoring that was done to properly move static QObject instances to different threads. I have not had an issue with that problem with version 2.18.1.

As for the normal CPU usage, there is probably something that can be done to reduce the load a bit but some of the extra load would be due to design choices. One factor is that the main mouse timer is running throughout the life of the application. When no mouse slots are active, the interval for that mouse timer is set to a higher value but it is still active and the linked slots will still be called. This slightly increases the CPU load but it helps reduce button lag significantly.

Another big factor is how gamepads are read. QJoyPad uses a QSocketNotifier instance to read a joystick device. QJoyPad will check the state of a joystick per run of the application event loop and the time between reads can vary. In antimicro, a timer is set up to call SDL_PeepEvents to check if SDL has detected any new events. The default poll rate is 10 ms but the timer can be set to a different time interval if desired. I haven't done any significant testing but it looks like, even at the default 10 ms poll rate, antimicro will poll a gamepad more often than QJoyPad and that increases the CPU load.

One final factor is regarding the Linux kernel. I am not sure what has changed with later Linux kernels but antimicro hardly uses any CPU time when using a later 3.x kernel (around 3.18 I believe) or a 4.x kernel. My underpowered Sabayon laptop is running a 4.0 kernel and antimicro hardly uses the CPU when using that kernel; I believe I have also seen similar results when using Fedora 21. On my Xubuntu 14.04 system or my SteamOS Brewmaster system running on my gaming PC, the CPU load is much greater.

I will look into it but I am not sure if anything can really be done that wouldn't result in adding extra button lag.

**Comment by Ryochan7** [comment] 2015-08-22 20:10
It looks like the simplest way to reduce the CPU load now is to merge the new event simulation thread with the gamepad poll thread. Currently, antimicro uses 3 threads overall. The gamepad polling routine runs in its own thread. Event simulation used to happen in the main GUI thread until those routines were split into a separate thread in version 2.18. With that small change, CPU usage is more in line with QJoyPad.

**Comment by namuol** [comment] 2015-08-22 21:19
@Ryochan7 Thanks for the timely response! I'd be happy to test this change if you have a branch for it or anything like that. :beers:

**Comment by Ryochan7** [comment] 2015-08-23 06:25
Actually, the change to using 2 threads doesn't make as big of a difference as I originally thought. However, I found a timer that wasn't being used as intended so it would fire events when unnecessary and that contributed to increasing the CPU load. That issue is enough to actually justify making a new point release.

**Comment by Ryochan7** [comment] 2015-08-24 18:18
Version 2.18.2 has just been pushed to the repository. Packages should be up soon. Hopefully the small changes in that version help with this problem a little bit.

**Comment by Ryochan7** [comment] 2015-09-02 05:27
Since there has been no update on this issue, I will have to assume that the version update resolved the problem. Thank you for bringing up this problem.

**Closed by Ryochan7** 2015-09-02 05:27 UTC
Labels: bug, enhancement
